services:
  - type: web
    name: hiveapi
    env: docker
    plan: starter
    autoDeploy: true
    region: oregon
    dockerfilePath: ./hiveapi/ops/Dockerfile
    dockerContext: ./hiveapi
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: hive-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hive-redis
          property: connectionString
      - key: REQUEST_SIGNATURE_REQUIRED
        value: "false"
      - key: PROMETHEUS_METRICS
        value: "true"
      - key: LOG_LEVEL
        value: "INFO"
      - key: ADMIN_ENABLED
        value: "true"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: AUTO_SEED
        value: "true"

  # Managed Redis service
  - type: redis
    name: hive-redis
    region: oregon
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

databases:
  - name: hive-db
    plan: starter
    region: oregon
    databaseName: hive
    user: hive
    ipAllowList:
      - source: service:hiveapi
